# Generated by Django 3.1.6 on 2021-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfMemeOwner', models.CharField(max_length=50)),
                ('caption', models.TextField()),
                ('memeUrl', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Memes_Informations',
            },
        ),
    ]
