# Generated by Django 3.1.6 on 2021-07-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memeinfo',
            options={'verbose_name_plural': "MemeInfo's"},
        ),
    ]
