# Generated by Django 3.1.6 on 2021-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0002_auto_20210715_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeinfo',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='memeUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='nameOfMemeOwner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
